/*
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.parser.antlr;

import com.google.inject.Inject;
import dk.sdu.mmmi.mdsd.parser.antlr.internal.InternalMath_expressionParser;
import dk.sdu.mmmi.mdsd.services.Math_expressionGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class Math_expressionParser extends AbstractAntlrParser {

	@Inject
	private Math_expressionGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMath_expressionParser createParser(XtextTokenStream stream) {
		return new InternalMath_expressionParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MathExp";
	}

	public Math_expressionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Math_expressionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
