/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.scoping;

import com.google.common.base.Objects;
import com.google.common.collect.Iterables;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.xtext.example.mydsl.myDsl.Entity;
import org.xtext.example.mydsl.myDsl.EntityRoot;
import org.xtext.example.mydsl.myDsl.Inheritance;
import org.xtext.example.mydsl.myDsl.Require;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MyDslScopeProvider extends AbstractMyDslScopeProvider {
  @Override
  public IScope getScope(final EObject context, final EReference reference) {
    IScope _xblockexpression = null;
    {
      boolean _matched = false;
      if (context instanceof Require) {
        _matched=true;
        return this.getScope(((Require)context));
      }
      _xblockexpression = super.getScope(context, reference);
    }
    return _xblockexpression;
  }

  public IScope getScope(final Require require) {
    IScope _xblockexpression = null;
    {
      final Entity entity = EcoreUtil2.<Entity>getContainerOfType(require, Entity.class);
      final EntityRoot root = EcoreUtil2.<EntityRoot>getContainerOfType(entity, EntityRoot.class);
      final Function1<Inheritance, Boolean> _function = (Inheritance it) -> {
        Entity _baseEntity = it.getBaseEntity();
        return Boolean.valueOf(Objects.equal(_baseEntity, entity));
      };
      final Inheritance inheritance = IterableExtensions.<Inheritance>findFirst(Iterables.<Inheritance>filter(root.getRelations(), Inheritance.class), _function);
      IScope _xifexpression = null;
      if ((inheritance == null)) {
        _xifexpression = Scopes.scopeFor(entity.getAttributes());
      } else {
        _xifexpression = Scopes.scopeFor(entity.getAttributes(), Scopes.scopeFor(inheritance.getSuperEntity().getAttributes()));
      }
      _xblockexpression = _xifexpression;
    }
    return _xblockexpression;
  }
}
