/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ui;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hash String Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mmmi.mdsd.ui.UiPackage#getHashStringType()
 * @model
 * @generated
 */
public interface HashStringType extends Type
{
} // HashStringType
