/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ui;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Use</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.ui.InputUse#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.ui.UiPackage#getInputUse()
 * @model
 * @generated
 */
public interface InputUse extends Exp
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(Input)
   * @see dk.sdu.mmmi.mdsd.ui.UiPackage#getInputUse_Ref()
   * @model
   * @generated
   */
  Input getRef();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.ui.InputUse#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Input value);

} // InputUse
