/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ui;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Row</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mmmi.mdsd.ui.UiPackage#getRow()
 * @model
 * @generated
 */
public interface Row extends Layout
{
} // Row
