/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ui;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mmmi.mdsd.ui.UiPackage#getStringType()
 * @model
 * @generated
 */
public interface StringType extends Type
{
} // StringType
