/*
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ui;

import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.Math_expression.ui.internal.Math_expressionActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Math_expressionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Math_expressionActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Math_expressionActivator activator = Math_expressionActivator.getInstance();
		return activator != null ? activator.getInjector(Math_expressionActivator.DK_SDU_MMMI_MDSD_MATH_EXPRESSION) : null;
	}

}
