/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.validation

import org.eclipse.xtext.validation.Check
import org.eclipse.xtext.EcoreUtil2
import dk.sdu.mmmi.mdsd.math.Variable
import dk.sdu.mmmi.mdsd.math.MathExp
import dk.sdu.mmmi.mdsd.math.MathPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MathValidator extends AbstractMathValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MathPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
	@Check
	def checkRepeatedGlobalVarDeclaration(Variable variable) {
		val mathExp = EcoreUtil2.getContainerOfType(variable, MathExp)
		val variables = mathExp.variables.filter(Variable)
		var count = 0
		for (var i = 0; i < variables.size; i++) {
			val current = variables.get(i)
			
			if (variable.name == current.name) {
				count++
			}
			
			if (count > 1) {
				error("Repeated", MathPackage.Literals.VARIABLE_TYPE__NAME)
				return
			}
		}
	}
}
