/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.Math_expressionRuntimeModule;
import dk.sdu.mmmi.mdsd.Math_expressionStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class Math_expressionIdeSetup extends Math_expressionStandaloneSetup {
  @Override
  public Injector createInjector() {
    Math_expressionRuntimeModule _math_expressionRuntimeModule = new Math_expressionRuntimeModule();
    Math_expressionIdeModule _math_expressionIdeModule = new Math_expressionIdeModule();
    return Guice.createInjector(Modules2.mixin(_math_expressionRuntimeModule, _math_expressionIdeModule));
  }
}
