/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.validation

import dk.sdu.mmmi.mdsd.math.VariableExp
import org.eclipse.xtext.validation.Check
import dk.sdu.mmmi.mdsd.math.MathExp

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MathValidator extends AbstractMathValidator {
	
	public static final String VAR_UNIQUE = 'var_unique'
	
	@Check
	def void unigueGlobal(VariableExp binding) {
		if((binding.eContainer as MathExp).varExp.filter[name == binding.name]) {
			error('Duplicate')
		}
		
	}
}
