/*
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.parser.antlr;

import com.google.inject.Inject;
import dk.sdu.mmmi.mdsd.parser.antlr.internal.InternalUiParser;
import dk.sdu.mmmi.mdsd.services.UiGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class UiParser extends AbstractAntlrParser {

	@Inject
	private UiGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalUiParser createParser(XtextTokenStream stream) {
		return new InternalUiParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "UI23";
	}

	public UiGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UiGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
