/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class Math_expressionUiModule extends AbstractMath_expressionUiModule {
  public Math_expressionUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
