/*
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import dk.sdu.mmmi.mdsd.ide.contentassist.antlr.internal.InternalMathParser;
import dk.sdu.mmmi.mdsd.services.MathGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MathParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MathGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MathGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getExpAccess().getAlternatives_1(), "rule__Exp__Alternatives_1");
			builder.put(grammarAccess.getFactorAccess().getAlternatives_1(), "rule__Factor__Alternatives_1");
			builder.put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
			builder.put(grammarAccess.getVariableTypeAccess().getAlternatives(), "rule__VariableType__Alternatives");
			builder.put(grammarAccess.getVariableAccess().getGroup(), "rule__Variable__Group__0");
			builder.put(grammarAccess.getExpAccess().getGroup(), "rule__Exp__Group__0");
			builder.put(grammarAccess.getExpAccess().getGroup_1_0(), "rule__Exp__Group_1_0__0");
			builder.put(grammarAccess.getExpAccess().getGroup_1_1(), "rule__Exp__Group_1_1__0");
			builder.put(grammarAccess.getFactorAccess().getGroup(), "rule__Factor__Group__0");
			builder.put(grammarAccess.getFactorAccess().getGroup_1_0(), "rule__Factor__Group_1_0__0");
			builder.put(grammarAccess.getFactorAccess().getGroup_1_1(), "rule__Factor__Group_1_1__0");
			builder.put(grammarAccess.getParenthesisAccess().getGroup(), "rule__Parenthesis__Group__0");
			builder.put(grammarAccess.getLetVariableAccess().getGroup(), "rule__LetVariable__Group__0");
			builder.put(grammarAccess.getMathExpAccess().getVariablesAssignment(), "rule__MathExp__VariablesAssignment");
			builder.put(grammarAccess.getVariableAccess().getNameAssignment_1(), "rule__Variable__NameAssignment_1");
			builder.put(grammarAccess.getVariableAccess().getExpAssignment_3(), "rule__Variable__ExpAssignment_3");
			builder.put(grammarAccess.getExpAccess().getRightAssignment_1_0_2(), "rule__Exp__RightAssignment_1_0_2");
			builder.put(grammarAccess.getExpAccess().getRightAssignment_1_1_2(), "rule__Exp__RightAssignment_1_1_2");
			builder.put(grammarAccess.getFactorAccess().getRightAssignment_1_0_2(), "rule__Factor__RightAssignment_1_0_2");
			builder.put(grammarAccess.getFactorAccess().getRightAssignment_1_1_2(), "rule__Factor__RightAssignment_1_1_2");
			builder.put(grammarAccess.getParenthesisAccess().getExpAssignment_1(), "rule__Parenthesis__ExpAssignment_1");
			builder.put(grammarAccess.getMathNumberAccess().getValueAssignment(), "rule__MathNumber__ValueAssignment");
			builder.put(grammarAccess.getLetVariableAccess().getNameAssignment_1(), "rule__LetVariable__NameAssignment_1");
			builder.put(grammarAccess.getLetVariableAccess().getValueAssignment_3(), "rule__LetVariable__ValueAssignment_3");
			builder.put(grammarAccess.getLetVariableAccess().getExpAssignment_5(), "rule__LetVariable__ExpAssignment_5");
			builder.put(grammarAccess.getVariableUseAccess().getRefAssignment(), "rule__VariableUse__RefAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MathGrammarAccess grammarAccess;

	@Override
	protected InternalMathParser createParser() {
		InternalMathParser result = new InternalMathParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MathGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MathGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
