/*
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ide

import com.google.inject.Guice
import dk.sdu.mmmi.mdsd.UiRuntimeModule
import dk.sdu.mmmi.mdsd.UiStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class UiIdeSetup extends UiStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new UiRuntimeModule, new UiIdeModule))
	}
	
}
