/*
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ui.tests;

import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.ui.ui.internal.UiActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class UiUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return UiActivator.getInstance().getInjector("dk.sdu.mmmi.mdsd.Ui");
	}

}
