/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class Math_expressionRuntimeModule extends AbstractMath_expressionRuntimeModule {
}
