/*
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.validation

import dk.sdu.mmmi.mdsd.math_expression.MathExp
import dk.sdu.mmmi.mdsd.math_expression.MathPackage
import dk.sdu.mmmi.mdsd.math_expression.VarBinding
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class Math_expressionValidator extends AbstractMath_expressionValidator {
	
	public static final String VAR_UNIQUE = 'var_unique'
	
	@Check
	def void uniqueGlobalVariableDefinition(VarBinding binding){
		if((binding.eContainer as MathExp).variables.filter[name == binding.name].size > 1)
			error("Duplicate global variable", MathPackage.eINSTANCE.binding_Name, VAR_UNIQUE)
	}
	
}
