/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.UiRuntimeModule;
import dk.sdu.mmmi.mdsd.UiStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class UiIdeSetup extends UiStandaloneSetup {
  @Override
  public Injector createInjector() {
    UiRuntimeModule _uiRuntimeModule = new UiRuntimeModule();
    UiIdeModule _uiIdeModule = new UiIdeModule();
    return Guice.createInjector(Modules2.mixin(_uiRuntimeModule, _uiIdeModule));
  }
}
