/*
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ui.tests;

import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.Math_expression.ui.internal.Math_expressionActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class Math_expressionUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Math_expressionActivator.getInstance().getInjector("dk.sdu.mmmi.mdsd.Math_expression");
	}

}
