/*
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class UiStandaloneSetup extends UiStandaloneSetupGenerated {

	def static void doSetup() {
		new UiStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
